export const USER_LOGIN = 'USER_LOGIN';
export const UPDATE_CONNECTED_USER = 'REGISTER_CONNECTED_USER';
export const GROUPS_LIST_UPDATE = 'GROUPS_LIST_UPDATE';

export const SIGR_SET_USER_NAME = 'SET_USER_NAME';
export const SIGR_CAST_VOTE = 'CAST_VOTE';
export const SIGR_CLEAR_VOTES = 'CLEAR_VOTES';
export const SIGR_SHOW_VOTES = 'SHOW_VOTES';
export const SIGR_LIST_GROUPS = 'SIGR_LIST_GROUPS';
export const SIGR_CREATE_GROUP = 'CREATE_GROUP';